name: test CI
on: [push]
jobs:
  e2e:
    name: Run tests on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.7.x', '18.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Check out ENS contracts
        uses: actions/checkout@master
        with:
          repository: ensdomains/ens-contracts
          path: './contracts'

      - name: Run local node
        run: cd ./contracts && yarn && npx hardhat node --hostname 127.0.0.1 &

      - name: Wait for local node
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          timeout: 5000
          resource: 127.0.0.1:8545

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

